server:
  port: 10855
spring:
  datasource:
    druid:
      username: root
      password: 1q2w3e
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.8.210.11:3306/sh_mlsh_life?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      initialSize: 5
      minIdle: 5
      maxActive: 200
      maxWait: 60000
  redis:
    sentinel:
      nodes: redis-dlock-aof.shanhui.me:27500,redis-dlock-aof.shanhui.me:27501
      master: mymaster17500
    timeout: 5000ms
#jobcenter回调地址
jobcenter:
  name: mlshapi
  port: 10855
  serverHost: jobcenter.55tuan.me
  serverPort: 9001
  zkAddress: zk1-1.55tuan.me:2181,zk1-2.55tuan.me:2181,zk1-3.55tuan.me:2181

ybconfig:
  shprivatekey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDKIEcebD7DUEU+9dF5dHewsdXnbrNjt2u8Qu1x7u446Myww6Mv0ZN6VMl84Lj3uEoRUed9lbzEn69fkZQfb+oAM4VXesRqDJdsHCVBZAqLrShnDF6I7sqcHCJ3lFW2aj+IAtqKWRDjM4xeO2Ws4Ia3vJh8CY241JNkHJt6RLHjgsWZJpkTaGFPVli/gYjCIArzImCpqM7ACu5HATkJq6YWeVkdkykpQgNK9HzYiNIsfvGvQjoTseTWsWQ0XuEBp/KJm5/yOm+ris79WouR0tRzwdsGhGLw3QOllDb2c+0IdHid4gcNTfJUhA3SEEKCMLg0o9EhkpUNtlyKuWAn1VkpAgMBAAECggEAKaxN/W/D4PED1d9IuQnSQ5Pmzjh8s+p1Q/NokTz50LHuweMUGh/TkD067YxHlotgegGxAKuGp+NkfQe+ylyAmloE++xL4rGF5rxG0hyWMAYbdmOOeh0BmP4T/SOQKHPvdVNhS3ThjnZqUmNcqy//lpJDvg8aMSli2hkr1SGkq4tE5VIs00s6/wCGYAeoepLdHjdZ4LGU0Abbu2igBm8XZnnyX8Eb9kzk7H2H/dlidfLFjKgCuOQCS0JRzRJVUphxJtEzizkTK8nMohCp9ufanMoKL0zVcy9SrQURNPJ9M4dXQkf4fWx9mW8qKV84HdDZkJoXT6vDHFDQtXSWz1npIQKBgQDr/A9qbuyIM3kBl4UcKNiL2BTiKIpWz3gf45uIjwe0+S23QBtmmZdwcqoOl997WH2ZJZ/j+jZDMi7DhuuReeOk5iewn0tPniPpmyZuBaW5crIoLcaY3Hfu/+NgE6TuT4Q8JZNj494TOwRB6b/Zf/9hg+Sm9m0Xd7rhlmSmxaXOYwKBgQDbRQvs6NcgADZcc1pjKMB0UuWhNntGpjwwaRME67pDdmR5Nl9wRTrOYqBv2xWNtXDVl8a5gv+9PfZUmfilYGa212V9twiehTLmXxJkCQjaC25y2/FiZ/hyPA1Uf5zI8/baOPdH93n4JdZtA9+dWyU5j8l5GkOZn+lZL/LhoFC6AwKBgQDnZMOg85+PdhljTDXDhPHBPmJL2MC9mrYJXt91qfo+pE8FbyDvHA/4vRavNJB4nC6b6t67Zu+qOBzOsQ9wGHr1iJDGiYwJR+GjAPVP0M3N5/91kl04KoaXneZQoTKKUwIxEA9UVW2+oZHtJ81s8itybSfZ56zU5Bwlc5jCRu/sTQKBgQDFotuX41sb5fUZqYOcAvxNHPcLMy80Q9vWiq7w7YRLEGiJdL/bUxspMW6Iw8EOpK8aZp5hUbkvGq1wHgQnE9ghD87T3GlxcH+rc6AA+L+4wTsBXkuZNjuSw5wEQK3R10v18Ai7Hk4apAg85JPmomPQGVEwzcKGssNCd1yFj9mTfwKBgQC51QNsr02gjoMER49SsgLyKAIT9IepR/sfZ0zfR25aWdBckrLGKQ7R6jbfASJWKW0JFc7WgUMNOaL0y+2upxljjZN/Nb6RCL5sqfAbpzzmau+eDFYKmFR7oYOBTLDEfianSRKXZ9cvnrj9xdqv2yyzrir8zULEsvEviBA6ESnPEQ==
  appkey: OPR:10027854372
  plateCode: 10027854372